# -*- coding: utf-8 -*-
"""real time.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kWNCmWHQ0Ex2oY4J0KX5nGOq2xNjJqRW
"""

!pip install SpeechRecognition

!pip install gtts

from gtts import gTTS

import speech_recognition as sr

model=sr.Recognizer()

!pip install pydub

mp3_file=r'/content/class.mp3'
from pydub import AudioSegment
from pydub.playback import play
audio=AudioSegment.from_file(mp3_file)
audio.export("temp1.wav",format="wav")

audio_file=r'/content/temp1.wav'
with sr.AudioFile(audio_file) as source:
  audio_data=model.record(source)
  text=model.recognize_google(audio_data)
  print(text)

pip install transformers

from transformers import pipeline

summarize=pipeline("summarization")

test=input('')

result=summarize(test)

result

analyser =pipeline('sentiment-analysis')

text_input=input("enter your text:")

result=analyser(text_input)

result

from transformers import pipeline

# Load a pre-trained question-answering pipeline from Hugging Face
qa_pipeline = pipeline("question-answering")

# Function to ask questions and get answers based on the provided context
def ask_user_questions():
    # Default context
    context = '''summary_text': " Recursion is just another way to create a loop but infinite Loops aren't very useful in practice . Recursive functions are not the right choice in every situation but they are very good for tree and graph traversals . In the next video I'll explain how to improve this with memoization'''

   # print("Welcome to the interactive story! Ask me any question about Luca's adventure.")

    # Loop to continuously take user questions
    while True:
        # Ask the user to input a question
        user_question = input("Ask a question (or type 'exit' to quit): ").lower()

        # Exit condition
        if user_question == 'exit':
            print("Goodbye!")
            break

        # Use the pipeline to get the answer from the model
        result = qa_pipeline(question=user_question, context=context)

        # Print the answer
        print("Answer:", result['answer'])

        # Ask if the user wants to ask another question
        continue_choice = input("Do you want to ask another question? (yes/no): ").lower()
        if continue_choice != 'yes':
          print("Goodbye!")
          # Corrected indentation for the break statement
          break  # Exit if the user does not want to continue

# Start the question-answering loop
ask_user_questions()

vqa_pipeline = pipeline("visual-question-answering")

image=r'/content/pexels-photo-2049259.jpeg'

question=input('enter a question to ask about image:')
result=vqa_pipeline(image,question)
print (result)