# -*- coding: utf-8 -*-
"""transmitters sub programs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iTnZFdh0TAxoen6-_qRYUuvwCDXlOKtY
"""

pip install transformers()

from transformers import pipeline

"""centiment analysis"""

analyser =pipeline('sentiment-analysis')

text_input=input("enter your text:")

result=analyser(text_input)

result

"""text generator"""

generage=pipeline("text-generation")

statement=input("enter the statement")

result = generage(statement,max_length=50,num_return_sequences=1)

result

"""entity recognition"""

named_entity_recognition=pipeline("ner")

text=input("enter the text")

result=named_entity_recognition(text)

result

"""question-answering"""

q_a=pipeline("question-answering")

result= q_a({'question':'Why did the villagers ignore the boy when he saw the real wolf?',
'context':"""
**The Boy Who Cried Wolf**
There once was a boy who grew bored while watching over the village sheep.
He wanted to make things more exciting. So, he yelled out that he saw a wolf chasing the
 sheep. All the villagers came running to drive the wolf away. However, they saw no wolf.
 The boy was amused, but the villagers were not. They told him not to do it again. Shortly
 after, he repeated this antic. The villagers came running again, only to find that he was
  lying. Later that day, the boy really sees a wolf sneaking amongst the flock. He jumped
  up and called out for help. But no one came this time because they thought he was still
  joking around. At sunset, the villagers looked for the boy. He had not returned with
  their sheep. They found him crying. He told them that there really was a wolf, and
  the entire flock was gone. An old man came to comfort him and told him that nobody
  would believe a liar even when they are being honest."""
  })

result

"""summarization"""

summarize=pipeline("summarization")

test=input('')

result=summarize(test,max_length=57)

result

"""multiple questions"""

story = """
📖 Story: The Boy Who Cried Wolf

There once was a boy who grew bored while watching over the village sheep.
He wanted to make things more exciting. So, he yelled out that he saw a wolf chasing the sheep.
All the villagers came running to drive the wolf away. However, they saw no wolf.
The boy was amused, but the villagers were not. They told him not to do it again.

Shortly after, he repeated this antic. The villagers came running again, only to find that he was lying.

Later that day, the boy really sees a wolf sneaking amongst the flock.
He jumped up and called out for help. But no one came this time because they thought he was still joking around.

At sunset, the villagers looked for the boy. He had not returned with their sheep.
They found him crying. He told them that there really was a wolf, and the entire flock was gone.

An old man came to comfort him and told him that nobody would believe a liar even when they are being honest.

Moral: Lying breaks trust.
"""

# Basic keyword-based logic
def smart_answer(question):
    q = question.lower()
    if "job" in q or "work" in q:
        return "The boy's job was to watch over the village sheep."
    elif "lie" in q:
        return "The boy lied about seeing a wolf when there wasn't one."
    elif "villagers" in q and "react" in q:
        return "They came running to help but found no wolf."
    elif "wolf" in q and "real" in q:
        return "Yes, the wolf was real the third time."
    elif "moral" in q:
        return "The moral is: Lying breaks trust."
    elif "end" in q or "flock" in q:
        return "The flock was lost because no one believed the boy when the real wolf came."
    elif "old man" in q:
        return "The old man told the boy that no one believes a liar even when they're honest."
    else:
        return "That's a good question. Think about what the story is trying to teach."

# Show the story
print(story)
print("\nAsk me anything about the story. Type 'exit' to quit.\n")

while True:
    user_input = input("Your question: ").strip().lower()
    if user_input in ["exit", "quit"]:
        print("Goodbye! 👋")
        break
    else:
        answer = smart_answer(user_input)
        print(f"✅ Answer: {answer}\n")

while True:
  q=input('enter your question')
  context=input("""
  Story: The Boy Who Cried Wolf

There once was a boy who grew bored while watching over the village sheep.
He wanted to make things more exciting. So, he yelled out that he saw a wolf chasing the sheep.
All the villagers came running to drive the wolf away. However, they saw no wolf.
The boy was amused, but the villagers were not. They told him not to do it again.

Shortly after, he repeated this antic. The villagers came running again, only to find that he was lying.

Later that day, the boy really sees a wolf sneaking amongst the flock.
He jumped up and called out for help. But no one came this time because they thought he was still joking around.

At sunset, the villagers looked for the boy. He had not returned with their sheep.
They found him crying. He told them that there really was a wolf, and the entire flock was gone.

An old man came to comfort him and told him that nobody would believe a liar even when they are being honest.

Moral: Lying breaks trust.
""")
  if q=='exit':
    break
    result=qa({
        'question':q,
        'context':context
    })
  else:
    print(smart_answer(q))

"""translator

"""

trans = pipeline("translation_en_to_de")

text=input('enter some text:')

result = trans(text)

result

f_n = pipeline('fill-mask')

text = input('Enter sentence <mask> ')

result = f_n(text)

result